vim.keymap.set("n", "<leader>ps", function()
    require('telescope.builtin').grep_string({ search = vim.fn.input("Grep For > ")})
end)
vim.keymap.set("n", "<C-p>", function()
    require('telescope.builtin').git_files()
end)
vim.keymap.set("n", "<Leader>pf", function()
    require('telescope.builtin').find_files()
end)
vim.keymap.set("n", "<Leader>ph", function()
    require('telescope.builtin').find_files({ hidden = true })
end)

vim.keymap.set("n", "<leader>pw", function()
    require('telescope.builtin').grep_string { search = vim.fn.expand("<cword>") }
end)
vim.keymap.set("n", "<leader>pb", function()
    require('telescope.builtin').buffers()
end)
vim.keymap.set("n", "<leader>vh", function()
    require('telescope.builtin').help_tags()
end)
vim.keymap.set("n", "<leader>gw", function()
    require('telescope').extensions.git_worktree.git_worktrees()
end)
vim.keymap.set("n", "<leader>gm", function()
    require('telescope').extensions.git_worktree.create_git_worktree()
end)
